FROM openresty/openresty:1.19.9.1-1-alpine-fat

RUN apk add git && \
    luarocks install lua-resty-http && \
    luarocks install lua-cjson && \
    luarocks install lua-resty-cookie && \
    luarocks install lua-resty-jwt